### ISSUE TITLE
Reservar una mesa

### ISSUE THREAD

**Issue by OscarNohGarma** [OscarNohGarma/Equipo-1-El-Abuelo#39]
Como: cliente

Quiero: poder reservar una mesa

Para: asistir en una ocasión importante

El cliente podrá reservar una mesa ingresando a una sección de la página y siguiendo el debido proceso, este será en forma de un formulario. El dueño podrá ver la reservación y confirmar al cliente que su mesa fue apartada.

**Comment by WoolyOlvel** [comment]
Frontend:

En una nueva sección de la página, se debe crear un formulario horizontal con un diseño tipo "card" de bordes redondeados, dividido en dos partes principales. La sección izquierda debe incluir, en la parte superior izquierda, el logotipo de "El Abuelo". Debajo del logotipo, se colocará una barra de progreso vertical con cuatro etapas importantes:

1. Personal: Información del Cliente
2. Reservar: Reservación de Mesa
3. Pagos: Métodos de Pago
4. ¡Listo!: Reservación Completa

En la sección derecha del formulario, se mostrará el título de la etapa actual y los campos requeridos para esa fase.

Etapa 1: Información del Cliente
En esta etapa, los campos requeridos son:

- Nombres
- Apellidos
- Número Telefónico

Debajo de los campos habrá dos botones: uno para avanzar a la siguiente etapa y otro para regresar a la etapa anterior (este último estará deshabilitado en la etapa 1). Cada etapa debe incluir validadores que impidan avanzar si algún campo está vacío, mostrando una alerta de error con SweetAlert2 en caso de intento fallido.

Etapa 2: Reservación de Mesa
Esta etapa incluirá los siguientes campos:

- Fecha de Reservación: Solo se podrán seleccionar fechas entre viernes y domingo, desde el día actual hasta un máximo de 6 meses en el futuro. No se podrán seleccionar fechas anteriores a la actual.
- Hora de Reservación: El horario permitido será de 7 pm a 12 am.
- Cantidad de Personas por Mesa: Un select permitirá elegir la cantidad de personas por mesa. Dependiendo de esta selección, aparecerá otro selector para elegir la ubicación de la mesa (interior o exterior).
- Aparecerá la etiqueta p en donde se indicará la cantidad de mesas totales cuando no se tenga seleccionado ninguna opción de los select disponibles, cuando se seleccione algún select se actualizará la cantidad de mesas totales a la cantidad de mesas disponible por persona y de acuerdo al lugar de la mesa.
- Cantidad de Mesas: Un input que mostrará la cantidad de mesas a reservar, el cual se actualizará dinámicamente según la selección de cantidad de personas y lugar de la mesa
- Costo por Mesa: Un input que mostrará el costo por mesa sin decoración, el cual se actualizará dinámicamente según la selección de mesas.

Además, habrá un selector para elegir la decoración de la mesa:

- Ninguna
- Romántica
- Cumpleaños
- Personalizada

Si se selecciona "Ninguna", aparecerá de inmediato el botón "Reservar Mesa", que llevará a la etapa 4. Si se elige "Personalizada", aparecerá un párrafo indicando que el usuario debe contactar al administrador para coordinar los detalles de la decoración.

Etapa 3: Métodos de Pago
En esta etapa, se mostrarán tres campos:

- Total de Mesas Reservadas
- Información del Banco
- Número de Cuenta para el Depósito

También se incluirá un input para subir archivos en formatos jpeg, jpg, png o heic, con un límite de 20 MB. Si se sube un archivo en un formato no permitido, se mostrará una alerta de error con SweetAlert2. Una vez seleccionada una imagen válida, se mostrará una vista previa de la misma. En esta etapa, el botón "Siguiente" será reemplazado por el botón "Reservar Mesa". Al presionar dicho botón, se mostrará una animación de éxito con SweetAlert2. Si no se ha subido el comprobante de pago, se mostrará un mensaje de error.

Etapa 4: ¡Listo! Reservación Finalizada

Esta etapa solo indicará que la reservación ha sido completada, y el usuario recibirá un mensaje de confirmación. En caso de problemas, se proporcionará el número del administrador para contacto. Habrá un botón que dirá "Reservar otra mesa", el cual reiniciará el proceso de reservación desde la primera etapa.

**Comment by WoolyOlvel** [comment]
Backend: 

Se necesita crear una tabla en la base de datos que almacene los datos del formulario de reservación. Los campos requeridos incluyen: nombre del cliente, apellido, número de teléfono, fecha de la reservación, hora de la reservación, cantidad de mesas reservadas, ubicación de las mesas (Interior o Exterior), costo por mesa (con y sin decoración), tipo de decoración seleccionada (si aplica), monto total de la reservación, tipo de banco y número de cuenta para el pago, y un campo para almacenar la ruta o archivo del comprobante de pago. Además, se debe considerar un campo que indique si se ha reservado otra mesa o no, y finalmente, un número de contacto para consultas.
