### ISSUE TITLE
Mostrar fotos de las instalaciones

### ISSUE THREAD

**Issue by WoolyOlvel** [OscarNohGarma/Equipo-1-El-Abuelo#6]
Como: dueño

Quiero: que se muestren fotos de las instalaciones.

Para: mostrar cómo es el establecimiento por dentro.

**Comment by WoolyOlvel** [comment]
En esta tarea, el enfoque principal fue exhibir fotografías relacionadas con las instalaciones de la cafetería "El Abuelo". En cada fotografía se añade una descripción para poder tener una idea más clara la parte del lugar que se esta mostrando

**Comment by OscarNohGarma** [comment]
En la página inicial se añadirá una sección con un encabezado que diga "Conoce nuestra cafetería" en el cual se deben de mostrar diferentes fotos de las instalaciones, con una descripción y encabezado en cada una, de ser posible abarcar hasta 4 imágenes, todas acomodadas en un grid estratégicamente para dar una apariencia mucho más estética
